services:
    postgres:
        image: postgres:16-alpine
        container_name: postgres-boni
        restart: always
        environment:
            POSTGRES_DB: bonidb
            POSTGRES_USER: boniuser
            POSTGRES_PASSWORD: bonipass
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin-boni
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@boni.com
            PGADMIN_DEFAULT_PASSWORD: bonipass
        ports:
            - "8080:80"
        depends_on:
            - postgres
        volumes:
            - pgadmin_data:/var/lib/pgadmin

volumes:
    postgres_data:
    pgadmin_data:
